
development:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  pool: 5
  username: sbhatla
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sample_test
  pool: 5
  username: sbhatla
  password:
  host: localhost
  port: 5432
